# Generated by Django 6.0.6 on 2026-06-24 21:01

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                (
                    "submission_id",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("payload", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CRE", "Created"),
                            ("SUB", "Submitted"),
                            ("PRO", "Processed"),
                            ("ERR", "Error"),
                        ],
                        default="CRE",
                        max_length=20,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pubmed_id", models.CharField(blank=True, max_length=20, null=True)),
                ("doi", models.CharField(blank=True, max_length=200, null=True)),
                ("title", models.TextField(blank=True)),
                ("authors", models.JSONField(default=list)),
                ("publication_year", models.IntegerField(blank=True, null=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Variant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ca_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("gene_symbol", models.CharField(max_length=50)),
                ("reference_sequence", models.CharField(max_length=100)),
                ("hgvs", models.TextField()),
                ("alternate_designations", models.TextField(blank=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_type", models.CharField(max_length=50)),
                ("id_value", models.CharField(max_length=100)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("id_type", "id_value"), name="unique_disease_id"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalBatch",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                (
                    "submission_id",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("payload", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CRE", "Created"),
                            ("SUB", "Submitted"),
                            ("PRO", "Processed"),
                            ("ERR", "Error"),
                        ],
                        default="CRE",
                        max_length=20,
                    ),
                ),
                ("added_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical batch",
                "verbose_name_plural": "historical batchs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDisease",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("id_type", models.CharField(max_length=50)),
                ("id_value", models.CharField(max_length=100)),
                ("added_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical disease",
                "verbose_name_plural": "historical diseases",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPublication",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("pubmed_id", models.CharField(blank=True, max_length=20, null=True)),
                ("doi", models.CharField(blank=True, max_length=200, null=True)),
                ("title", models.TextField(blank=True)),
                ("authors", models.JSONField(default=list)),
                ("publication_year", models.IntegerField(blank=True, null=True)),
                ("added_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical publication",
                "verbose_name_plural": "historical publications",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalVariant",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "ca_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("gene_symbol", models.CharField(max_length=50)),
                ("reference_sequence", models.CharField(max_length=100)),
                ("hgvs", models.TextField()),
                ("alternate_designations", models.TextField(blank=True)),
                ("added_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical variant",
                "verbose_name_plural": "historical variants",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalClassification",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("local_id", models.UUIDField(default=uuid.uuid4)),
                ("linking_id", models.UUIDField(default=uuid.uuid4)),
                ("germline_classification", models.CharField(max_length=100)),
                ("mode_of_inheritance", models.CharField(max_length=200)),
                ("date_last_evaluated", models.DateField(blank=True, null=True)),
                ("comment_on_classification", models.TextField(blank=True)),
                ("collection_method", models.CharField(max_length=100)),
                ("allele_origin", models.CharField(max_length=100)),
                ("affected_status", models.CharField(max_length=100)),
                ("scv", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PND", "Pending"),
                            ("BAT", "In Batch"),
                            ("SUB", "Submitted"),
                            ("PRO", "Processed"),
                            ("ERR", "Error"),
                        ],
                        default="PND",
                        max_length=3,
                    ),
                ),
                ("source_app", models.CharField(max_length=50)),
                ("schema_version", models.CharField(max_length=20)),
                ("raw_payload", models.JSONField()),
                ("added_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="classification.batch",
                    ),
                ),
                (
                    "disease",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="classification.disease",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="classification.variant",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical classification",
                "verbose_name_plural": "historical classifications",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Classification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("local_id", models.UUIDField(default=uuid.uuid4)),
                ("linking_id", models.UUIDField(default=uuid.uuid4)),
                ("germline_classification", models.CharField(max_length=100)),
                ("mode_of_inheritance", models.CharField(max_length=200)),
                ("date_last_evaluated", models.DateField(blank=True, null=True)),
                ("comment_on_classification", models.TextField(blank=True)),
                ("collection_method", models.CharField(max_length=100)),
                ("allele_origin", models.CharField(max_length=100)),
                ("affected_status", models.CharField(max_length=100)),
                ("scv", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PND", "Pending"),
                            ("BAT", "In Batch"),
                            ("SUB", "Submitted"),
                            ("PRO", "Processed"),
                            ("ERR", "Error"),
                        ],
                        default="PND",
                        max_length=3,
                    ),
                ),
                ("source_app", models.CharField(max_length=50)),
                ("schema_version", models.CharField(max_length=20)),
                ("raw_payload", models.JSONField()),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="classifications",
                        to="classification.batch",
                    ),
                ),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classifications",
                        to="classification.disease",
                    ),
                ),
                (
                    "publications",
                    models.ManyToManyField(
                        blank=True, related_name="classifications", to="classification.publication"
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classifications",
                        to="classification.variant",
                    ),
                ),
            ],
        ),
    ]
