# Generated by Django 6.0.6 on 2026-07-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classification", "0002_rename_ca_id_historicalvariant_car_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classification",
            name="affiliation",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="historicalclassification",
            name="affiliation",
            field=models.CharField(default="", max_length=100),
        ),
    ]
