# Generated by Django 6.0.6 on 2026-07-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classification", "0003_classification_affiliation_historicalclassification_affiliation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classification",
            name="affiliation",
            field=models.CharField(default="", max_length=5),
        ),
        migrations.AlterField(
            model_name="historicalclassification",
            name="affiliation",
            field=models.CharField(default="", max_length=5),
        ),
    ]
