# Generated by Django 6.0.6 on 2026-06-24 21:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalvariant",
            old_name="ca_id",
            new_name="car_id",
        ),
        migrations.RenameField(
            model_name="variant",
            old_name="ca_id",
            new_name="car_id",
        ),
    ]
