# Generated by Django 6.0.6 on 2026-07-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curation", "0003_curation_affiliation_historicalcuration_affiliation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curation",
            name="affiliation",
            field=models.CharField(default="", max_length=5),
        ),
        migrations.AlterField(
            model_name="historicalcuration",
            name="affiliation",
            field=models.CharField(default="", max_length=5),
        ),
    ]
